language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4"
before_script:
  - npm install -g gulp
script: gulp
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df469ab72a9dce18622b
